import { cache } from "react";
import "server-only";

import { createHash, randomBytes, timingSafeEqual } from "node:crypto";
import { cookies } from "next/headers";

import { isSupabaseConfigured } from "@/lib/supabase/admin";
import type { PlayerSessionRow } from "@/lib/supabase/types";
import { findPlayerSession, touchPlayerSession, SESSION_TTL_MS } from "./repository";
import type { PlayerIdentity } from "./schema";

export const PLAYER_COOKIE = "cf_player";

/**
 * 32 bytes of CSPRNG output, base64url encoded.
 *
 * This is the entire credential — possession of it is the authorisation, since
 * a guest has no account to check it against. It therefore has to be long
 * enough that guessing is hopeless and generated by `randomBytes`, never
 * `Math.random`.
 */
export function createSessionToken(): string {
  return randomBytes(32).toString("base64url");
}

/** Lowercase hex SHA-256, matching the column's constraint. */
export function hashSessionToken(token: string): string {
  return createHash("sha256").update(token).digest("hex");
}

/**
 * Constant-time comparison of two token hashes.
 *
 * The database lookup does the real matching, so this exists for the paths
 * that compare in application code. Lengths are checked first because
 * `timingSafeEqual` throws on a mismatch rather than returning false.
 */
export function tokenHashesMatch(a: string, b: string): boolean {
  const left = Buffer.from(a);
  const right = Buffer.from(b);
  if (left.length !== right.length) return false;
  return timingSafeEqual(left, right);
}

/**
 * Cookie attributes.
 *
 * `httpOnly` keeps the token away from any script on the page, which matters
 * because it is a bearer credential. `sameSite: "lax"` still arrives when a
 * player follows a link from a QR scanner app or a message, which is exactly
 * how they will arrive, while blocking cross-site POSTs.
 */
function cookieOptions() {
  return {
    httpOnly: true,
    secure: process.env.NODE_ENV === "production",
    sameSite: "lax" as const,
    path: "/",
    maxAge: Math.floor(SESSION_TTL_MS / 1000),
  };
}

/**
 * Writes the session cookie. Only callable from a Server Action or Route
 * Handler — Next.js cannot set headers once a Server Component has streamed.
 */
export async function setPlayerCookie(token: string): Promise<void> {
  (await cookies()).set(PLAYER_COOKIE, token, cookieOptions());
}

export async function clearPlayerCookie(): Promise<void> {
  (await cookies()).delete(PLAYER_COOKIE);
}

/**
 * Resolves the current guest, or null.
 *
 * Safe to call from a Server Component: it only reads. Renewal is a write, so
 * it is deliberately fire-and-forget inside the repository rather than
 * something this function's caller has to think about.
 */
/* Once per request, however many loaders ask: the room page asks from
   several places, and each answer was a lookup and a presence write. */
export const getPlayerSession = cache(
  async function getPlayerSession(): Promise<PlayerSessionRow | null> {
    if (!isSupabaseConfigured()) return null;

    const token = (await cookies()).get(PLAYER_COOKIE)?.value;
    if (!token) return null;

    const session = await findPlayerSession(hashSessionToken(token));
    if (!session) return null;

    await touchPlayerSession(session);
    return session;
  },
);

/** The subset of a session a page may render. */
export function toIdentity(session: PlayerSessionRow): PlayerIdentity {
  return { id: session.id, displayName: session.display_name };
}

export async function getPlayerIdentity(): Promise<PlayerIdentity | null> {
  const session = await getPlayerSession();
  return session ? toIdentity(session) : null;
}
