-- The founder's catalog, written down and kept out of sight.
--
-- Every row here is status='draft': invisible in the store, in every
-- wardrobe, in every pack pool, and to the unlock-all grant. They exist
-- so the console has something to curate - the founder's plan is to go
-- through them one at a time, delete what is not good enough, and gather
-- the survivors into sets with release dates.
--
-- Costs are all zero on purpose. A draft cosmetic is never bought; when
-- one goes live inside a pack, the pack's price is what is paid. Any that
-- later go on sale individually get their price then, in the console.
--
-- Kinds are the catalog's own (ring, border, pattern, animation,
-- background, scene, nameplate, title, badge) rather than the live
-- catalog's (frame, holo, effect) - see the previous migration for why.

begin;

insert into public.cosmetics
  (slug, kind, name, description, cost_embers, requires_earned, sort_order, status)
values
  ('ring-inferno', 'ring', 'Inferno', 'Orange flame licking around the picture.', 0, null, 10, 'draft'),
  ('ring-frozen', 'ring', 'Frozen', 'An icy blue crystalline edge.', 0, null, 20, 'draft'),
  ('ring-electric', 'ring', 'Electric', 'Small lightning arcs around the rim.', 0, null, 30, 'draft'),
  ('ring-galaxy', 'ring', 'Galaxy', 'A slow purple and blue nebula.', 0, null, 40, 'draft'),
  ('ring-gold-foil', 'ring', 'Gold Foil', 'Reflective gold, catching the light.', 0, null, 50, 'draft'),
  ('ring-rainbow-foil', 'ring', 'Rainbow Foil', 'Every colour, moving.', 0, null, 60, 'draft'),
  ('ring-manga', 'ring', 'Manga', 'Black and white comic speed lines.', 0, null, 70, 'draft'),
  ('ring-pixel', 'ring', 'Pixel', 'An animated 8-bit border.', 0, null, 80, 'draft'),
  ('ring-glitch', 'ring', 'Glitch', 'Occasional RGB displacement.', 0, null, 90, 'draft'),
  ('ring-vaporwave', 'ring', 'Vaporwave', 'Pink and cyan glow.', 0, null, 100, 'draft'),
  ('ring-aurora', 'ring', 'Aurora', 'Green and blue, slowly shifting.', 0, null, 110, 'draft'),
  ('ring-ember', 'ring', 'Ember', 'Tiny sparks floating upward.', 0, null, 120, 'draft'),
  ('ring-smoke', 'ring', 'Smoke', 'Dark smoke, barely moving.', 0, null, 130, 'draft'),
  ('ring-water', 'ring', 'Water', 'A rippling blue edge.', 0, null, 140, 'draft'),
  ('ring-sakura', 'ring', 'Sakura', 'Petals drifting around the picture.', 0, null, 150, 'draft'),
  ('ring-heart', 'ring', 'Heart', 'Small hearts floating up.', 0, null, 160, 'draft'),
  ('ring-crown', 'ring', 'Crown', 'A little crown above the picture.', 0, null, 170, 'draft'),
  ('ring-starfield', 'ring', 'Starfield', 'Stars in orbit.', 0, null, 180, 'draft'),
  ('ring-meteor', 'ring', 'Meteor', 'A shooting star, now and then.', 0, null, 190, 'draft'),
  ('ring-diamond', 'ring', 'Diamond', 'Crystal facets catching the light.', 0, null, 200, 'draft'),
  ('ring-black-flame', 'ring', 'Black Flame', 'Flame in black, for the quietly frightening.', 0, null, 210, 'draft'),
  ('ring-white-flame', 'ring', 'White Flame', 'Flame in white, cold and bright.', 0, null, 220, 'draft'),
  ('ring-retro-arcade', 'ring', 'Retro Arcade', 'Cabinet colours, chunky and bright.', 0, null, 230, 'draft'),
  ('ring-crt', 'ring', 'CRT', 'A faint scanline drifting down.', 0, null, 240, 'draft'),
  ('ring-prestige', 'ring', 'Prestige', 'The one that says how far you have come.', 0, null, 250, 'draft'),
  ('border-classic-black', 'border', 'Classic Black', 'The default, drawn properly.', 0, null, 10, 'draft'),
  ('border-white-pearl', 'border', 'White Pearl', 'Soft white with a shifting sheen.', 0, null, 20, 'draft'),
  ('border-silver', 'border', 'Silver', 'Cool metal, plainly finished.', 0, null, 30, 'draft'),
  ('border-gold', 'border', 'Gold', 'Warm metal, worn openly.', 0, null, 40, 'draft'),
  ('border-rose-gold', 'border', 'Rose Gold', 'Pink metal, softer than gold.', 0, null, 50, 'draft'),
  ('border-platinum', 'border', 'Platinum', 'Pale metal, quietly expensive.', 0, null, 60, 'draft'),
  ('border-bronze', 'border', 'Bronze', 'Old metal, warm and dull.', 0, null, 70, 'draft'),
  ('border-emerald', 'border', 'Emerald', 'Deep green, cut like a stone.', 0, null, 80, 'draft'),
  ('border-ruby', 'border', 'Ruby', 'Deep red, cut like a stone.', 0, null, 90, 'draft'),
  ('border-sapphire', 'border', 'Sapphire', 'Deep blue, cut like a stone.', 0, null, 100, 'draft'),
  ('border-amethyst', 'border', 'Amethyst', 'Deep purple, cut like a stone.', 0, null, 110, 'draft'),
  ('border-obsidian', 'border', 'Obsidian', 'Black glass with a hard shine.', 0, null, 120, 'draft'),
  ('border-ice', 'border', 'Ice', 'Frost creeping in from the corners.', 0, null, 130, 'draft'),
  ('border-fire', 'border', 'Fire', 'Flame along the edge.', 0, null, 140, 'draft'),
  ('border-lightning', 'border', 'Lightning', 'Arcs running the border.', 0, null, 150, 'draft'),
  ('border-toxic', 'border', 'Toxic', 'Acid green, faintly glowing.', 0, null, 160, 'draft'),
  ('border-neon-cyan', 'border', 'Neon Cyan', 'A cyan tube, lit.', 0, null, 170, 'draft'),
  ('border-neon-pink', 'border', 'Neon Pink', 'A pink tube, lit.', 0, null, 180, 'draft'),
  ('border-neon-orange', 'border', 'Neon Orange', 'An orange tube, lit.', 0, null, 190, 'draft'),
  ('border-neon-purple', 'border', 'Neon Purple', 'A purple tube, lit.', 0, null, 200, 'draft'),
  ('border-rainbow', 'border', 'Rainbow', 'The whole spectrum, edge to edge.', 0, null, 210, 'draft'),
  ('border-aurora', 'border', 'Aurora', 'Green and blue, slowly shifting.', 0, null, 220, 'draft'),
  ('border-galaxy', 'border', 'Galaxy', 'Deep space wrapped around the card.', 0, null, 230, 'draft'),
  ('border-manga', 'border', 'Manga', 'Black and white, inked.', 0, null, 240, 'draft'),
  ('border-pixel', 'border', 'Pixel', 'Chunky 8-bit edging.', 0, null, 250, 'draft'),
  ('border-glitch', 'border', 'Glitch', 'RGB displacement, occasionally.', 0, null, 260, 'draft'),
  ('border-carbon-fiber', 'border', 'Carbon Fiber', 'Woven black, matte.', 0, null, 270, 'draft'),
  ('border-chrome', 'border', 'Chrome', 'Mirror metal.', 0, null, 280, 'draft'),
  ('border-holographic-chrome', 'border', 'Holographic Chrome', 'Mirror metal, in every colour.', 0, null, 290, 'draft'),
  ('border-cracked-stone', 'border', 'Cracked Stone', 'Grey stone, split through.', 0, null, 300, 'draft'),
  ('border-lava-cracks', 'border', 'Lava Cracks', 'Stone with fire underneath.', 0, null, 310, 'draft'),
  ('border-frosted-glass', 'border', 'Frosted Glass', 'Translucent and cold.', 0, null, 320, 'draft'),
  ('border-circuit-board', 'border', 'Circuit Board', 'Traces and solder points.', 0, null, 330, 'draft'),
  ('border-starfield', 'border', 'Starfield', 'A field of stars.', 0, null, 340, 'draft'),
  ('border-treasure-map', 'border', 'Treasure Map', 'Aged parchment and ink.', 0, null, 350, 'draft'),
  ('border-gold-filigree', 'border', 'Gold Filigree', 'Playing-card scrollwork.', 0, null, 360, 'draft'),
  ('border-comic-panel', 'border', 'Comic Panel', 'Heavy ink, like a panel border.', 0, null, 370, 'draft'),
  ('border-vhs', 'border', 'VHS', 'Tape colours and tracking lines.', 0, null, 380, 'draft'),
  ('border-crt-arcade', 'border', 'CRT Arcade', 'Scanlines and phosphor glow.', 0, null, 390, 'draft'),
  ('border-black-flame', 'border', 'Black Flame', 'Flame in black.', 0, null, 400, 'draft'),
  ('border-white-flame', 'border', 'White Flame', 'Flame in white.', 0, null, 410, 'draft'),
  ('border-cosmic-flame', 'border', 'Cosmic Flame', 'Flame in the colours of deep space.', 0, null, 420, 'draft'),
  ('border-milestone', 'border', 'Milestone', 'Gets wilder the more trades you confirm.', 0, null, 430, 'draft'),
  ('pattern-classic-rainbow', 'pattern', 'Classic Rainbow', 'The even sheen of a standard foil.', 0, null, 10, 'draft'),
  ('pattern-prism', 'pattern', 'Prism', 'Two rainbows crossing.', 0, null, 20, 'draft'),
  ('pattern-galaxy', 'pattern', 'Galaxy', 'Deep and starry.', 0, null, 30, 'draft'),
  ('pattern-starburst', 'pattern', 'Starburst', 'Rays from the centre.', 0, null, 40, 'draft'),
  ('pattern-cracked-ice', 'pattern', 'Cracked Ice', 'The shattered-glass foil.', 0, null, 50, 'draft'),
  ('pattern-confetti', 'pattern', 'Confetti', 'Scattered flecks of colour.', 0, null, 60, 'draft'),
  ('pattern-glitter', 'pattern', 'Glitter', 'Fine sparkle across the face.', 0, null, 70, 'draft'),
  ('pattern-diamond', 'pattern', 'Diamond', 'Faceted, catching light in blocks.', 0, null, 80, 'draft'),
  ('pattern-spiral', 'pattern', 'Spiral', 'A slow turning coil.', 0, null, 90, 'draft'),
  ('pattern-waves', 'pattern', 'Waves', 'Rolling bands of colour.', 0, null, 100, 'draft'),
  ('pattern-lightning', 'pattern', 'Lightning', 'Forked arcs under the surface.', 0, null, 110, 'draft'),
  ('pattern-flame', 'pattern', 'Flame', 'Fire under the surface.', 0, null, 120, 'draft'),
  ('pattern-digital-grid', 'pattern', 'Digital Grid', 'A lit grid, receding.', 0, null, 130, 'draft'),
  ('pattern-matrix-rain', 'pattern', 'Matrix Rain', 'Falling characters, green.', 0, null, 140, 'draft'),
  ('pattern-pixel-sparkle', 'pattern', 'Pixel Sparkle', '8-bit glints.', 0, null, 150, 'draft'),
  ('pattern-manga-screentone', 'pattern', 'Manga Screentone', 'Halftone dots, monochrome.', 0, null, 160, 'draft'),
  ('pattern-aurora', 'pattern', 'Aurora', 'Green and blue, shifting.', 0, null, 170, 'draft'),
  ('pattern-cosmic-dust', 'pattern', 'Cosmic Dust', 'Fine particles, drifting.', 0, null, 180, 'draft'),
  ('pattern-meteor-shower', 'pattern', 'Meteor Shower', 'Streaks across the face.', 0, null, 190, 'draft'),
  ('pattern-bubbles', 'pattern', 'Bubbles', 'Rising and popping.', 0, null, 200, 'draft'),
  ('pattern-hearts', 'pattern', 'Hearts', 'Small hearts across the face.', 0, null, 210, 'draft'),
  ('pattern-sakura-petals', 'pattern', 'Sakura Petals', 'Petals across the face.', 0, null, 220, 'draft'),
  ('pattern-snowflakes', 'pattern', 'Snowflakes', 'Falling, each one different.', 0, null, 230, 'draft'),
  ('pattern-gold-flecks', 'pattern', 'Gold Flecks', 'Warm metal, scattered.', 0, null, 240, 'draft'),
  ('pattern-silver-flecks', 'pattern', 'Silver Flecks', 'Cool metal, scattered.', 0, null, 250, 'draft'),
  ('pattern-oil-slick', 'pattern', 'Oil Slick', 'Iridescent, unpredictable.', 0, null, 260, 'draft'),
  ('pattern-vhs-rainbow', 'pattern', 'VHS Rainbow', 'Tape colours, banded.', 0, null, 270, 'draft'),
  ('pattern-checkerboard', 'pattern', 'Checkerboard', 'Alternating, shifting.', 0, null, 280, 'draft'),
  ('pattern-honeycomb', 'pattern', 'Honeycomb', 'Six sided, tiled.', 0, null, 290, 'draft'),
  ('pattern-hex-grid', 'pattern', 'Hex Grid', 'A lit hexagonal mesh.', 0, null, 300, 'draft'),
  ('pattern-star-shapes', 'pattern', 'Star Shapes', 'Stars, tiled across the face.', 0, null, 310, 'draft'),
  ('pattern-cardflare-flame', 'pattern', 'CardFlare Flame', 'The mark''s flame, repeating.', 0, null, 320, 'draft'),
  ('pattern-cardflare-logos', 'pattern', 'CardFlare Logos', 'Tiny marks, tiled.', 0, null, 330, 'draft'),
  ('pattern-secret-rare', 'pattern', 'Secret Rare', 'Diagonal rainbow streaks.', 0, null, 340, 'draft'),
  ('pattern-manga-monochrome', 'pattern', 'Manga Monochrome', 'Shimmer with the colour taken out.', 0, null, 350, 'draft'),
  ('anim-still', 'animation', 'Still', 'No movement at all.', 0, null, 10, 'draft'),
  ('anim-shimmer', 'animation', 'Shimmer', 'A gentle sheen, passing.', 0, null, 20, 'draft'),
  ('anim-pulse', 'animation', 'Pulse', 'A slow breath of light.', 0, null, 30, 'draft'),
  ('anim-orbit', 'animation', 'Orbit', 'A point circling the card.', 0, null, 40, 'draft'),
  ('anim-float', 'animation', 'Float', 'Rising and settling, very slowly.', 0, null, 50, 'draft'),
  ('anim-tilt', 'animation', 'Tilt', 'A subtle 3D lean.', 0, null, 60, 'draft'),
  ('anim-sparkle', 'animation', 'Sparkle', 'Occasional glints.', 0, null, 70, 'draft'),
  ('anim-ember-sparks', 'animation', 'Ember Sparks', 'Sparks rising off the card.', 0, null, 80, 'draft'),
  ('anim-flame-edge', 'animation', 'Flame Edge', 'Fire along the border.', 0, null, 90, 'draft'),
  ('anim-electric-arcs', 'animation', 'Electric Arcs', 'Arcs jumping the edges.', 0, null, 100, 'draft'),
  ('anim-snowfall', 'animation', 'Snowfall', 'Snow across the face.', 0, null, 110, 'draft'),
  ('anim-rain', 'animation', 'Rain', 'Rain across the face.', 0, null, 120, 'draft'),
  ('anim-sakura-petals', 'animation', 'Sakura Petals', 'Petals drifting past.', 0, null, 130, 'draft'),
  ('anim-cosmic-particles', 'animation', 'Cosmic Particles', 'Dust moving through space.', 0, null, 140, 'draft'),
  ('anim-floating-stars', 'animation', 'Floating Stars', 'Stars rising slowly.', 0, null, 150, 'draft'),
  ('anim-pixel-particles', 'animation', 'Pixel Particles', '8-bit motes.', 0, null, 160, 'draft'),
  ('anim-glitch-flicker', 'animation', 'Glitch Flicker', 'An occasional stutter.', 0, null, 170, 'draft'),
  ('anim-scanline', 'animation', 'Scanline', 'A line drifting down.', 0, null, 180, 'draft'),
  ('anim-light-sweep', 'animation', 'Light Sweep', 'A bar of light crossing.', 0, null, 190, 'draft'),
  ('anim-spotlight-sweep', 'animation', 'Spotlight Sweep', 'A soft light passing over.', 0, null, 200, 'draft'),
  ('anim-holo-flare', 'animation', 'Holo Flare', 'A flare travelling the face.', 0, null, 210, 'draft'),
  ('anim-ripple', 'animation', 'Ripple', 'Rings spreading from a point.', 0, null, 220, 'draft'),
  ('anim-heart-particles', 'animation', 'Heart Particles', 'Hearts rising.', 0, null, 230, 'draft'),
  ('anim-smoke', 'animation', 'Smoke', 'Smoke curling off the edge.', 0, null, 240, 'draft'),
  ('anim-aura', 'animation', 'Aura', 'A glow that breathes.', 0, null, 250, 'draft'),
  ('anim-shockwave', 'animation', 'Shockwave', 'A ring, every few seconds.', 0, null, 260, 'draft'),
  ('anim-meteor-streak', 'animation', 'Meteor Streak', 'A streak across, now and then.', 0, null, 270, 'draft'),
  ('anim-breathe', 'animation', 'Breathe', 'The card gently swells and settles.', 0, null, 280, 'draft'),
  ('anim-scroll-shine', 'animation', 'Scroll Shine', 'Shines when scrolled into view.', 0, null, 290, 'draft'),
  ('anim-tilt-shine', 'animation', 'Tilt Shine', 'Shines with the phone''s tilt.', 0, null, 300, 'draft'),
  ('anim-flare-burst', 'animation', 'Flare Burst', 'A rare burst when somebody opens your profile.', 0, null, 310, 'draft'),
  ('bg-plain-charcoal', 'background', 'Plain Charcoal', 'The default, dark and quiet.', 0, null, 10, 'draft'),
  ('bg-cardflare-lime', 'background', 'CardFlare Lime', 'The brand''s own glow.', 0, null, 20, 'draft'),
  ('bg-night-sky', 'background', 'Night Sky', 'Clear, dark, a few stars.', 0, null, 30, 'draft'),
  ('bg-galaxy', 'background', 'Galaxy', 'Deep space and colour.', 0, null, 40, 'draft'),
  ('bg-sunset', 'background', 'Sunset', 'Warm light going down.', 0, null, 50, 'draft'),
  ('bg-pixel-city', 'background', 'Pixel City', 'A skyline in 8-bit.', 0, null, 60, 'draft'),
  ('bg-pixel-night-sky', 'background', 'Pixel Night Sky', '8-bit stars.', 0, null, 70, 'draft'),
  ('bg-lgs-table', 'background', 'LGS Table', 'The counter you actually trade on.', 0, null, 80, 'draft'),
  ('bg-tournament-hall', 'background', 'Tournament Hall', 'Long tables and bright light.', 0, null, 90, 'draft'),
  ('bg-card-shop-shelves', 'background', 'Card Shop Shelves', 'Boxes and sleeves behind you.', 0, null, 100, 'draft'),
  ('bg-binder-page', 'background', 'Binder Page', 'Nine pockets, well used.', 0, null, 110, 'draft'),
  ('bg-playmat', 'background', 'Playmat', 'Cloth and stitching.', 0, null, 120, 'draft'),
  ('bg-manga-panels', 'background', 'Manga Panels', 'Inked frames behind the cards.', 0, null, 130, 'draft'),
  ('bg-wanted-posters', 'background', 'Wanted Posters', 'Paper, nailed up.', 0, null, 140, 'draft'),
  ('bg-treasure-room', 'background', 'Treasure Room', 'Gold in the dark.', 0, null, 150, 'draft'),
  ('bg-pirate-deck', 'background', 'Pirate Deck', 'Rigging and timber.', 0, null, 160, 'draft'),
  ('bg-neon-city', 'background', 'Neon City', 'Signs in the rain.', 0, null, 170, 'draft'),
  ('bg-vaporwave-grid', 'background', 'Vaporwave Grid', 'Pink horizon, endless grid.', 0, null, 180, 'draft'),
  ('bg-arcade', 'background', 'Arcade', 'Cabinets glowing in a dark room.', 0, null, 190, 'draft'),
  ('bg-fire', 'background', 'Fire', 'Flame behind the glass.', 0, null, 200, 'draft'),
  ('bg-ice', 'background', 'Ice', 'Frost behind the glass.', 0, null, 210, 'draft'),
  ('bg-lightning-storm', 'background', 'Lightning Storm', 'Cloud lit from inside.', 0, null, 220, 'draft'),
  ('bg-sakura-garden', 'background', 'Sakura Garden', 'Blossom and quiet.', 0, null, 230, 'draft'),
  ('bg-underwater', 'background', 'Underwater', 'Light coming down through water.', 0, null, 240, 'draft'),
  ('bg-cloudscape', 'background', 'Cloudscape', 'Above the weather.', 0, null, 250, 'draft'),
  ('bg-space', 'background', 'Space', 'Nothing, beautifully.', 0, null, 260, 'draft'),
  ('bg-black-void', 'background', 'Black Void', 'Absolutely nothing.', 0, null, 270, 'draft'),
  ('bg-gold-luxury', 'background', 'Gold Luxury', 'Deep black and warm metal.', 0, null, 280, 'draft'),
  ('bg-holographic-foil', 'background', 'Holographic Foil', 'The whole wall, foiled.', 0, null, 290, 'draft'),
  ('bg-cardflare-pattern', 'background', 'CardFlare Pattern', 'The mark, repeating.', 0, null, 300, 'draft'),
  ('scene-falling-embers', 'scene', 'Falling Embers', 'Embers drifting down the page.', 0, null, 10, 'draft'),
  ('scene-shooting-stars', 'scene', 'Shooting Stars', 'Streaks across the background.', 0, null, 20, 'draft'),
  ('scene-snow', 'scene', 'Snow', 'Snow over everything.', 0, null, 30, 'draft'),
  ('scene-rain', 'scene', 'Rain', 'Rain over everything.', 0, null, 40, 'draft'),
  ('scene-sakura-petals', 'scene', 'Sakura Petals', 'Petals drifting across.', 0, null, 50, 'draft'),
  ('scene-floating-holo-shards', 'scene', 'Floating Holo Shards', 'Foil fragments, turning.', 0, null, 60, 'draft'),
  ('scene-drifting-cards', 'scene', 'Drifting Cards', 'Tiny cards moving in the background.', 0, null, 70, 'draft'),
  ('scene-flame-wisps', 'scene', 'Flame Wisps', 'Small flames rising.', 0, null, 80, 'draft'),
  ('scene-lightning-flashes', 'scene', 'Lightning Flashes', 'The page lights, occasionally.', 0, null, 90, 'draft'),
  ('scene-pixel-stars', 'scene', 'Pixel Stars', '8-bit stars.', 0, null, 100, 'draft'),
  ('scene-aurora', 'scene', 'Aurora', 'Green and blue across the top.', 0, null, 110, 'draft'),
  ('scene-galaxy-particles', 'scene', 'Galaxy Particles', 'Dust moving slowly.', 0, null, 120, 'draft'),
  ('scene-manga-speed-lines', 'scene', 'Manga Speed Lines', 'Lines converging on the middle.', 0, null, 130, 'draft'),
  ('scene-spotlight', 'scene', 'Spotlight', 'A light that follows your finger.', 0, null, 140, 'draft'),
  ('scene-parallax', 'scene', 'Parallax', 'The background moves as you scroll.', 0, null, 150, 'draft'),
  ('scene-flare-entrance', 'scene', 'Flare Entrance', 'A flare shoots across when the profile loads.', 0, null, 160, 'draft'),
  ('scene-avatar-entrance', 'scene', 'Avatar Entrance', 'Your picture arrives with a flourish.', 0, null, 170, 'draft'),
  ('scene-showcase-entrance', 'scene', 'Showcase Entrance', 'Your cards deal themselves in.', 0, null, 180, 'draft'),
  ('scene-veteran-shine', 'scene', 'Veteran Shine', 'A shine for 100 confirmed trades and up.', 0, null, 190, 'draft'),
  ('name-ember-name', 'nameplate', 'Ember Name', 'Your name in the brand''s orange.', 0, null, 10, 'draft'),
  ('name-lime-name', 'nameplate', 'Lime Name', 'Your name in the brand''s green.', 0, null, 20, 'draft'),
  ('name-frost-name', 'nameplate', 'Frost Name', 'Your name in cold blue.', 0, null, 30, 'draft'),
  ('name-rose-name', 'nameplate', 'Rose Name', 'Your name in pink.', 0, null, 40, 'draft'),
  ('name-gradient-name', 'nameplate', 'Gradient Name', 'Two colours, blended.', 0, null, 50, 'draft'),
  ('name-holographic-name', 'nameplate', 'Holographic Name', 'Every colour, shifting.', 0, null, 60, 'draft'),
  ('name-gold-name', 'nameplate', 'Gold Name', 'Your name in warm metal.', 0, null, 70, 'draft'),
  ('name-shimmer-name', 'nameplate', 'Shimmer Name', 'A sheen passing through the letters.', 0, null, 80, 'draft'),
  ('name-pixel-font', 'nameplate', 'Pixel Font', 'Your name in 8-bit type.', 0, null, 90, 'draft'),
  ('name-manga-font', 'nameplate', 'Manga Font', 'Your name inked.', 0, null, 100, 'draft'),
  ('name-glitch-name', 'nameplate', 'Glitch Name', 'Your name, occasionally displaced.', 0, null, 110, 'draft'),
  ('name-flame-name', 'nameplate', 'Flame Name', 'Your name on fire.', 0, null, 120, 'draft'),
  ('name-ice-name', 'nameplate', 'Ice Name', 'Your name in frost.', 0, null, 130, 'draft'),
  ('title-custom-tagline', 'title', 'Custom Tagline', 'A line you write yourself.', 0, null, 10, 'draft'),
  ('title-trade-milestone', 'title', 'Trade Milestone', 'How many trades you have confirmed.', 0, null, 20, 'draft'),
  ('title-collector', 'title', 'Collector', 'For the ones who keep everything.', 0, null, 30, 'draft'),
  ('title-closer', 'title', 'Closer', 'For the ones who finish trades.', 0, null, 40, 'draft'),
  ('title-regular', 'title', 'Regular', 'For the ones always at the counter.', 0, null, 50, 'draft'),
  ('badge-founder', 'badge', 'Founder', 'Was here at the beginning.', 0, null, 10, 'draft'),
  ('badge-beta-tester', 'badge', 'Beta Tester', 'Broke it before anyone else could.', 0, null, 20, 'draft'),
  ('badge-vendor', 'badge', 'Vendor', 'Sells at shows.', 0, null, 30, 'draft'),
  ('badge-lgs-staff', 'badge', 'LGS Staff', 'Runs the counter.', 0, null, 40, 'draft'),
  ('badge-tournament-organizer', 'badge', 'Tournament Organizer', 'Runs the event.', 0, null, 50, 'draft'),
  ('badge-early-adopter', 'badge', 'Early Adopter', 'Signed up in the first season.', 0, null, 60, 'draft'),
  ('badge-100-trades', 'badge', '100 Trades', 'One hundred confirmed.', 0, null, 70, 'draft'),
  ('badge-500-trades', 'badge', '500 Trades', 'Five hundred confirmed.', 0, null, 80, 'draft'),
  ('badge-1000-trades', 'badge', '1000 Trades', 'One thousand confirmed.', 0, null, 90, 'draft')
on conflict (slug) do nothing;

commit;
