import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

/**
 * Every iOS permission the app asks for has a sentence explaining it.
 *
 * This exists because the first build of the location feature crashed
 * the app dead on the home screen:
 *
 *   "This app is missing usage descriptions, so location services will
 *    fail. Add one of the `NSLocation*UsageDescription` keys to your
 *    bundle's Info.plist."
 *
 * Not an exception - RCTFatal, the whole app gone. A missing usage
 * string is not something JavaScript can catch or a try/catch can
 * soften, so it cannot be handled at runtime and has to be caught here.
 *
 * `mobile/ios` is generated by prebuild and gitignored, so the built
 * Info.plist is not a thing this repo can check. `app.json` is the
 * source it is generated FROM, and it is what this walks.
 */
const config = JSON.parse(readFileSync("mobile/app.json", "utf8")) as {
  expo: {
    plugins: (string | [string, Record<string, unknown>])[];
    ios: { infoPlist: Record<string, unknown> };
  };
};

const { plugins, ios } = config.expo;

const usesPlugin = (name: string) =>
  plugins.some((entry) => (Array.isArray(entry) ? entry[0] : entry) === name);

const optionsFor = (name: string) => {
  const entry = plugins.find((p) => Array.isArray(p) && p[0] === name);
  return Array.isArray(entry) ? entry[1] : {};
};

describe("iOS permission strings", () => {
  it("explains location, in our own words", () => {
    expect(usesPlugin("expo-location")).toBe(true);

    /* All three, because the plugin writes all three whatever we ask
       for - and the one we do NOT set gets the plugin's own default,
       "Allow $(PRODUCT_NAME) to access your location", which is a
       sentence we did not write going in front of App Review. */
    for (const key of [
      "NSLocationWhenInUseUsageDescription",
      "NSLocationAlwaysAndWhenInUseUsageDescription",
      "NSLocationAlwaysUsageDescription",
    ]) {
      const why = ios.infoPlist[key];
      expect(why, `${key} must be set`).toBeTypeOf("string");
      expect(why as string).toContain("CardFlare");
      expect((why as string).length).toBeGreaterThan(40);
    }
  });

  it("never asks to follow anybody around in the background", () => {
    /* A list of shops has no use for a position while the app is
       closed, and the entitlement alone invites a question at review
       that we would have no answer to. */
    const options = optionsFor("expo-location");
    expect(options.isIosBackgroundLocationEnabled).toBe(false);
    expect(options.isAndroidBackgroundLocationEnabled).toBe(false);
    expect(options.locationAlwaysAndWhenInUsePermission).toBeUndefined();
  });

  it("explains the camera too", () => {
    /* The rule is not "location has a string", it is "every permission
       has one". Adding a permission without its sentence is the crash
       above, and it lands on whichever screen asks first. */
    expect(ios.infoPlist.NSCameraUsageDescription).toBeTypeOf("string");
  });
});
